# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.8-slim

# EXPOSE 8000

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

RUN apt-get update -y && \
    apt-get install -y git

COPY ./website/requirements.txt .

# Install pip requirements
RUN python -m pip install -r requirements.txt

WORKDIR /website

# Creates a non-root user with an explicit UID and adds permission to access the /website folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /website
USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
# File wsgi.py was not found in subfolder: 'ResumeBuilder'. Please enter the Python path to wsgi file.
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "RESUMEBUILDER.wsgi"]
