FROM ubuntu

# Install Nginx.
RUN \
  apt update && \
  apt install -y software-properties-common && \
  apt update && \
  add-apt-repository -y ppa:nginx/stable && \
  apt-get update && \
  apt-get install -y nginx certbot python3-certbot-nginx && \
  rm -rf /var/lib/apt/lists/* && \
  chown -R www-data:www-data /var/lib/nginx && \
  certbot --nginx -d api.givemyresume.tech -d app.givemyresume.tech -n -m balasubhayu99@gmail.com --eff-email --agree-tos

# Define mountable directories.
VOLUME ["/etc/nginx/sites-enabled", "/etc/nginx/certs", "/etc/nginx/conf.d", "/var/log/nginx", "/var/www/html"]

# Define working directory.
WORKDIR /etc/nginx

# Define default command.
CMD ["nginx"]

# Expose ports.
EXPOSE 80
EXPOSE 443
EXPOSE 8000
EXPOSE 8001